
name : Install CppUnit Test

on :
  push :
    branches : [ "master", "develop" ]

jobs :
  install_cppunit_job:
    runs-on : ubuntu-latest
    name : install CppUnit

    steps :
      - uses : actions/checkout@v4

      - id : foo
        uses : takahiro-itou/install-cppunit-action@develop
        with :
          install-prefix : ${{ github.workspace }}/tools/cppunit

      - run : |
          pwd
          echo "${{ github.workspace }}"
          ls -alR "${{ github.workspace }}/tools/"
        shell : bash
