
name : Install CppUnit Test

on :
  push :
    branches : [ "master", "develop" ]

jobs :
  install_cppunit_job:
    runs-on : ubuntu-latest
    name : install CppUnit

    strategy :
      fail-fast : false

      matrix :
        with-cppunit :
          - no
          - tools/cppunit

    steps :
      - uses : actions/checkout@v4

      - name : Print Install Dir
        run : |
          echo "workspace = ${{ github.workspace }}"
          echo "target    = ${{ matrix.with-cppunit }}"
        shell : bash

      - if : ${{ matrix.with-cppunit != 'no' }}
        name : Install CppUnit
        uses : takahiro-itou/install-cppunit-action@v1
        with :
          install-prefix : "${{ github.workspace }}/${{ matrix.with-cppunit }}"

      - name : Post-Show Workspace
        run : |
          pwd
          echo "${{ github.workspace }}"
          ls -lR "${{ github.workspace }}"
        shell : bash
